services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
