substitutions:
  name: ikea-speaker
  friendly_name: IKEA Speaker
  board: seeed_xiao_esp32s3
  pin_i2s_lrclk: GPIO07
  pin_i2s_bclk: GPIO09
  pin_i2s_dout: GPIO08


# --- BEGIN COMMON TEMPLATE ---

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board}
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  logs:
    wifi: INFO
    api: INFO
    mdns: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret gen_api

# Enable ESPHome OTA update
ota:
  - platform: esphome
    password: !secret gen_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret fallback_password

captive_portal:

# Time
time:
    - platform: homeassistant
      id: time_homeassistant

    - platform: sntp
      id: time_sntp
      timezone: America/Detroit
      servers:
          - 10.10.1.1
          - 1.pool.ntp.org

binary_sensor:
  - platform: status
    name: "Status" 

# -- pause button start --

  - platform: gpio
    pin: 
      number: 04
      mode: INPUT_PULLDOWN
      inverted: false # Assume button connects to GND
    name: "Button Play"
    on_press:
      - media_player.toggle: external_media_player 

  - platform: gpio
    pin: 
      number: 43
      mode: INPUT_PULLDOWN
      inverted: false # Assume button connects to GND
    name: "Button BT"
    on_press:
      - media_player.mute: external_media_player 

# -- pause button end --


# --- END COMMON TEMPLATE ---    


psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

# -- AUIDO --

i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: ${pin_i2s_lrclk}
    i2s_bclk_pin: ${pin_i2s_bclk}

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    i2s_audio_id: i2s_bus
    dac_type: external
    i2s_dout_pin: ${pin_i2s_dout}
    sample_rate: 44100
    buffer_duration: 1000ms
    bits_per_sample: 16bit

  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_audio_speaker
    num_channels: 1
    source_speakers:
      - id: announcement_mixing_input
      - id: media_mixing_input

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 44100
  
  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 44100

media_player:
  - platform: speaker
    id: external_media_player
    name: None
    internal: False
    volume_min: 0.4
    volume_max: 0.95
    volume_increment: 0.15
    announcement_pipeline:
      speaker: announcement_resampling_speaker
      format: FLAC
      num_channels: 1 
      sample_rate: 44100
    media_pipeline:
      speaker: media_resampling_speaker
      format: FLAC 
      num_channels: 2
      sample_rate: 44100
